# Esercizio implementazione funzioni di predizione KNN

Importo il dataset e divido i dati di train e i dati di test

In [1]:
from sklearn import datasets

data = datasets.load_iris()

In [2]:

X = data['data']
y = data['target']

print('X shape:', X.shape, 'y shape:', y.shape)

X shape: (150, 4) y shape: (150,)


Faccio uno shuffle del dataset per omogeneizzare i dati

In [66]:
import numpy as np
from numpy.random import default_rng

rnd = default_rng(seed = 12)

In [67]:
#Genero una permutazione da 0 a 150 che vado a mischiare
permutation = rnd.permutation(len(y))

#Aggiorno il dataset
X = X[permutation]
y = y[permutation]

In [68]:
#Separo train e test
n_test = int(0.1 * X.shape[0])
n_train = X.shape[0] - n_test
X_train, y_train = X[0:n_train], y[0:n_train]
X_test, y_test = X[n_train:], y[n_train:]

Calcolo il vettore delle distanze dal punto x_new ad ogni punto della matrice di train (X_train)

In [69]:
x_new = X_train[13]

In [70]:
distanza = []

for x_tr_i in X_train:
    d = np.sqrt(np.sum((x_new-x_tr_i)**2))
    distanza.append(d)

Ora trovo i K punti più vicini

In [71]:
k=4
k_neighbors = np.argsort(distanza)[:k]

In [72]:
k_neighbors

array([13,  7, 99, 94], dtype=int64)

Faccio la predizione!

In [73]:
y_new_pred = np.argmax(np.bincount(y_train[k_neighbors], minlength = 3))

In [74]:
y_new_pred

2

Ora definisco le funzioni esercizio

In [75]:
def predict_single(x_test, k, X_train, y_train):
    distanze = []

    for i in range(len(X_train)):
        d = np.sqrt(np.sum((X_train[i]-x_test)**2))
        distanze.append(d)
    
    #Trovo i punti piu vicini
    k_n = np.argsort(distanze)[:k]

    #Faccio la predizione
    y_pred = np.argmax(np.bincount(y_train[k_n], minlength=3))

    return y_pred
    
def knn_predict(X_test, k, X_train, y_train):

    y_predicted = []

    for x_test in X_test:
        y_predicted.append(predict_single(x_test, k, X_train, y_train))
    
    return y_predicted

In [76]:
predicted = knn_predict(X_test, 4, X_train, y_train)
predicted == y_test

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [34]:
y_test

array([1, 0, 2, 2, 2, 1, 2, 0, 2, 2, 1, 1, 1, 2, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 2, 1, 1, 0, 0, 0])

In [42]:
y_test

array([1, 0, 2, 2, 2, 1, 2, 0, 2, 2, 1, 1, 1, 2, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 2, 1, 1, 0, 0, 0])