<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

**Obiettivo:** creare un modello predittivo per risolvere un problema di classificazione attraverso l'utilizzo di KNN, seguendo la pipeline vista a lezione.
 

**Dataset:**
Il dataset da utilizzare contiene i risultati dell’analisi chimica di vini prodotti da tre diversi coltivatori Italiani: dovrai capire il tipo di vino a partire dai suoi valori chimici.

Puoi caricare il dataset direttamente dalla libreria di Scikit-learn: https://scikit-learn.org/stable/datasets/toy_dataset.html#wine-recognition-dataset.

In [20]:
from sklearn import datasets

data = datasets.load_wine()

In [21]:
X = data['data']
y = data['target']

print('X shape:', X.shape, 'y shape:', y.shape)

X shape: (178, 13) y shape: (178,)


In [22]:
import numpy as np
from numpy.random import default_rng

rnd = default_rng(seed = 12)

In [23]:
#Genero una permutazione da 0 a 150 che vado a mischiare
permutation = rnd.permutation(len(y))

#Aggiorno il dataset
X = X[permutation]
y = y[permutation]

In [24]:
#Separo train e test
n_test = int(0.2 * X.shape[0])
n_train = X.shape[0] - n_test
X_train, y_train = X[0:n_train], y[0:n_train]
X_test, y_test = X[n_train:], y[n_train:]

In [25]:
x_new = X_train[13]

distanza = []

for x_tr_i in X_train:
    d = np.sqrt(np.sum((x_new-x_tr_i)**2))
    distanza.append(d)

In [26]:
k=4
k_neighbors = np.argsort(distanza)[:k]

k_neighbors

array([ 13,  70,  35, 117], dtype=int64)

In [27]:
y_new_pred = np.argmax(np.bincount(y_train[k_neighbors], minlength = 3))

y_new_pred

2

In [28]:
def predict_single(x_test, k, X_train, y_train):
    distanze = []

    for i in range(len(X_train)):
        d = np.sqrt(np.sum((X_train[i]-x_test)**2))
        distanze.append(d)
    
    #Trovo i punti piu vicini
    k_n = np.argsort(distanze)[:k]

    #Faccio la predizione
    y_pred = np.argmax(np.bincount(y_train[k_n], minlength=3))

    return y_pred
    
def knn_predict(X_test, k, X_train, y_train):

    y_predicted = []

    for x_test in X_test:
        y_predicted.append(predict_single(x_test, k, X_train, y_train))
    
    return y_predicted

predicted = knn_predict(X_test, 4, X_train, y_train)
predicted == y_test

array([ True,  True,  True,  True,  True,  True, False, False,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True, False,  True,  True,  True,  True,  True, False,
       False,  True, False,  True,  True,  True,  True,  True])

In [29]:
predicted = knn_predict(X_test, 4, X_train, y_train)
predicted == y_test

array([ True,  True,  True,  True,  True,  True, False, False,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True, False,  True,  True,  True,  True,  True, False,
       False,  True, False,  True,  True,  True,  True,  True])