<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [1]:
import pandas as pd
import numpy as np

In [3]:
data  = pd.read_csv('adult.csv')

In [4]:
data

age workclass  fnlwgt     education  education.num      marital.status  \
0       90         ?   77053       HS-grad              9             Widowed   
1       82   Private  132870       HS-grad              9             Widowed   
2       66         ?  186061  Some-college             10             Widowed   
3       54   Private  140359       7th-8th              4            Divorced   
4       41   Private  264663  Some-college             10           Separated   
...    ...       ...     ...           ...            ...                 ...   
32556   22   Private  310152  Some-college             10       Never-married   
32557   27   Private  257302    Assoc-acdm             12  Married-civ-spouse   
32558   40   Private  154374       HS-grad              9  Married-civ-spouse   
32559   58   Private  151910       HS-grad              9             Widowed   
32560   22   Private  201490       HS-grad              9       Never-married   

              occupation   relationship   race     sex  capital.gain  \
0                      ?  Not-in-family  White  Female             0   
1        Exec-managerial  Not-in-family  White  Female             0   
2                      ?      Unmarried  Black  Female             0   
3      Machine-op-inspct      Unmarried  White  Female             0   
4         Prof-specialty      Own-child  White  Female             0   
...                  ...            ...    ...     ...           ...   
32556    Protective-serv  Not-in-family  White    Male             0   
32557       Tech-support           Wife  White  Female             0   
32558  Machine-op-inspct        Husband  White    Male             0   
32559       Adm-clerical      Unmarried  White  Female             0   
32560       Adm-clerical      Own-child  White    Male             0   

       capital.loss  hours.per.week native.country income  
0              4356              40  United-States  <=50K  
1              4356              18  United-States  <=50K  
2              4356              40  United-States  <=50K  
3              3900              40  United-States  <=50K  
4              3900              40  United-States  <=50K  
...             ...             ...            ...    ...  
32556             0              40  United-States  <=50K  
32557             0              38  United-States  <=50K  
32558             0              40  United-States   >50K  
32559             0              40  United-States  <=50K  
32560             0              20  United-States  <=50K  

[32561 rows x 15 columns]

In [5]:
data.income.value_counts()

<=50K    24720
>50K      7841
Name: income, dtype: int64

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32561 non-null  int64 
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64 
 3   education       32561 non-null  object
 4   education.num   32561 non-null  int64 
 5   marital.status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital.gain    32561 non-null  int64 
 11  capital.loss    32561 non-null  int64 
 12  hours.per.week  32561 non-null  int64 
 13  native.country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [7]:
data.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education.num',
       'marital.status', 'occupation', 'relationship', 'race', 'sex',
       'capital.gain', 'capital.loss', 'hours.per.week', 'native.country',
       'income'],
      dtype='object')

In [8]:
data.head()

age workclass  fnlwgt     education  education.num marital.status  \
0   90         ?   77053       HS-grad              9        Widowed   
1   82   Private  132870       HS-grad              9        Widowed   
2   66         ?  186061  Some-college             10        Widowed   
3   54   Private  140359       7th-8th              4       Divorced   
4   41   Private  264663  Some-college             10      Separated   

          occupation   relationship   race     sex  capital.gain  \
0                  ?  Not-in-family  White  Female             0   
1    Exec-managerial  Not-in-family  White  Female             0   
2                  ?      Unmarried  Black  Female             0   
3  Machine-op-inspct      Unmarried  White  Female             0   
4     Prof-specialty      Own-child  White  Female             0   

   capital.loss  hours.per.week native.country income  
0          4356              40  United-States  <=50K  
1          4356              18  United-States  <=50K  
2          4356              40  United-States  <=50K  
3          3900              40  United-States  <=50K  
4          3900              40  United-States  <=50K

In [9]:
data[['education','education.num']].head(20)

education  education.num
0        HS-grad              9
1        HS-grad              9
2   Some-college             10
3        7th-8th              4
4   Some-college             10
5        HS-grad              9
6           10th              6
7      Doctorate             16
8        HS-grad              9
9   Some-college             10
10     Doctorate             16
11   Prof-school             15
12     Bachelors             13
13       Masters             14
14     Doctorate             16
15   Prof-school             15
16          11th              7
17       Masters             14
18    Assoc-acdm             12
19     Bachelors             13

In [10]:
categorical = ['workclass','marital.status','occupation','relationship','race','sex']
numerical = ['age','education.num','capital.gain','capital.loss','hours.per.week']
label = 'income'

In [11]:
data

age workclass  fnlwgt     education  education.num      marital.status  \
0       90         ?   77053       HS-grad              9             Widowed   
1       82   Private  132870       HS-grad              9             Widowed   
2       66         ?  186061  Some-college             10             Widowed   
3       54   Private  140359       7th-8th              4            Divorced   
4       41   Private  264663  Some-college             10           Separated   
...    ...       ...     ...           ...            ...                 ...   
32556   22   Private  310152  Some-college             10       Never-married   
32557   27   Private  257302    Assoc-acdm             12  Married-civ-spouse   
32558   40   Private  154374       HS-grad              9  Married-civ-spouse   
32559   58   Private  151910       HS-grad              9             Widowed   
32560   22   Private  201490       HS-grad              9       Never-married   

              occupation   relationship   race     sex  capital.gain  \
0                      ?  Not-in-family  White  Female             0   
1        Exec-managerial  Not-in-family  White  Female             0   
2                      ?      Unmarried  Black  Female             0   
3      Machine-op-inspct      Unmarried  White  Female             0   
4         Prof-specialty      Own-child  White  Female             0   
...                  ...            ...    ...     ...           ...   
32556    Protective-serv  Not-in-family  White    Male             0   
32557       Tech-support           Wife  White  Female             0   
32558  Machine-op-inspct        Husband  White    Male             0   
32559       Adm-clerical      Unmarried  White  Female             0   
32560       Adm-clerical      Own-child  White    Male             0   

       capital.loss  hours.per.week native.country income  
0              4356              40  United-States  <=50K  
1              4356              18  United-States  <=50K  
2              4356              40  United-States  <=50K  
3              3900              40  United-States  <=50K  
4              3900              40  United-States  <=50K  
...             ...             ...            ...    ...  
32556             0              40  United-States  <=50K  
32557             0              38  United-States  <=50K  
32558             0              40  United-States   >50K  
32559             0              40  United-States  <=50K  
32560             0              20  United-States  <=50K  

[32561 rows x 15 columns]

In [16]:
#eliminazione 
for c in categorical:
    data = data[data[c]!='?']

In [17]:
data

age workclass  fnlwgt     education  education.num      marital.status  \
1       82   Private  132870       HS-grad              9             Widowed   
3       54   Private  140359       7th-8th              4            Divorced   
4       41   Private  264663  Some-college             10           Separated   
5       34   Private  216864       HS-grad              9            Divorced   
6       38   Private  150601          10th              6           Separated   
...    ...       ...     ...           ...            ...                 ...   
32556   22   Private  310152  Some-college             10       Never-married   
32557   27   Private  257302    Assoc-acdm             12  Married-civ-spouse   
32558   40   Private  154374       HS-grad              9  Married-civ-spouse   
32559   58   Private  151910       HS-grad              9             Widowed   
32560   22   Private  201490       HS-grad              9       Never-married   

              occupation   relationship   race     sex  capital.gain  \
1        Exec-managerial  Not-in-family  White  Female             0   
3      Machine-op-inspct      Unmarried  White  Female             0   
4         Prof-specialty      Own-child  White  Female             0   
5          Other-service      Unmarried  White  Female             0   
6           Adm-clerical      Unmarried  White    Male             0   
...                  ...            ...    ...     ...           ...   
32556    Protective-serv  Not-in-family  White    Male             0   
32557       Tech-support           Wife  White  Female             0   
32558  Machine-op-inspct        Husband  White    Male             0   
32559       Adm-clerical      Unmarried  White  Female             0   
32560       Adm-clerical      Own-child  White    Male             0   

       capital.loss  hours.per.week native.country income  
1              4356              18  United-States  <=50K  
3              3900              40  United-States  <=50K  
4              3900              40  United-States  <=50K  
5              3770              45  United-States  <=50K  
6              3770              40  United-States  <=50K  
...             ...             ...            ...    ...  
32556             0              40  United-States  <=50K  
32557             0              38  United-States  <=50K  
32558             0              40  United-States   >50K  
32559             0              40  United-States  <=50K  
32560             0              20  United-States  <=50K  

[30718 rows x 15 columns]

In [ ]:
categorical = ['workclass','marital.status','occupation','relationship','race','sex']
numerical = ['age','education.num','capital.gain','capital.loss','hours.per.week']
label = 'income'

In [18]:
#encoding

from sklearn.preprocessing import StandardScaler, OneHotEncoder

# labels
y = data[label].values

y = OneHotEncoder(sparse=False, drop='if_binary').fit_transform(y.reshape(-1, 1)).squeeze()

# oppure con pandas
# y = pd.get_dummies(y, drop_first=True).values.squeeze()

y

array([0., 0., 0., ..., 1., 0., 0.])

In [19]:
data.income

1        <=50K
3        <=50K
4        <=50K
5        <=50K
6        <=50K
         ...  
32556    <=50K
32557    <=50K
32558     >50K
32559    <=50K
32560    <=50K
Name: income, Length: 30718, dtype: object

In [20]:
X_cat = data[categorical]
X_num = data[numerical]

In [22]:
#encoding categorical

ohe = OneHotEncoder(sparse=False, drop='if_binary')
X_cat = ohe.fit_transform(X_cat.values)

# oppure con pandas
# X_cat = pd.get_dummies(X_cat, columns=categorical).values

print(X_cat.shape)


(30718, 40)


In [23]:
X_cat

array([[0., 0., 1., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 1., 0.],
       ...,
       [0., 0., 1., ..., 0., 1., 1.],
       [0., 0., 1., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 1., 1.]])

In [24]:
y.shape

(30718,)

In [25]:
X_cat.shape

(30718, 40)

In [26]:
X_num.shape

(30718, 5)

In [29]:
X = np.concatenate([X_cat,X_num], axis =1)

In [62]:
X

array([[0.000e+00, 0.000e+00, 1.000e+00, ..., 0.000e+00, 4.356e+03,
        1.800e+01],
       [0.000e+00, 0.000e+00, 1.000e+00, ..., 0.000e+00, 3.900e+03,
        4.000e+01],
       [0.000e+00, 0.000e+00, 1.000e+00, ..., 0.000e+00, 3.900e+03,
        4.000e+01],
       ...,
       [0.000e+00, 0.000e+00, 1.000e+00, ..., 0.000e+00, 0.000e+00,
        4.000e+01],
       [0.000e+00, 0.000e+00, 1.000e+00, ..., 0.000e+00, 0.000e+00,
        4.000e+01],
       [0.000e+00, 0.000e+00, 1.000e+00, ..., 0.000e+00, 0.000e+00,
        2.000e+01]])

In [63]:
y

array([0., 0., 0., ..., 1., 0., 0.])

$X_{t}$:
$$p_{ct} := \frac{1}{N_{t}}\sum_{x_{i}\in X_{t}} 1(y_{i} = c)$$

Entropia (H) del sottospazio $X_{t}$:

$$H(X_{t}) := -\sum_{c=1}^{c}p_{ct}\log(p_{ct})$$

In [34]:
a = np.bincount(y.astype(int), minlength=2)/len(y)
a

array([0.75096035, 0.24903965])

In [64]:
data['income'].value_counts()

<=50K    23068
>50K      7650
Name: income, dtype: int64

In [36]:
# TO DO definire entropia e considerare il caso in cui esiste
# la forma indeterminata 0*-inf per capire 
#

def entropy(y):
    #modificata per risolvere il problema della forma indeterminata
    p = np.bincount(y.astype(int), minlength=2)/len(y)
    if np.sum(np.isclose(p, 0)) >0: #ci torniamo sabato prossimo
        e = 0
    else:
        e = - np.sum(p * np.log2(p))# forma indeterminata con 0*-inf
    return e


In [37]:
#separazione tra train e test

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state=42)

In [38]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((24574, 45), (6144, 45), (24574,), (6144,))

In [ ]:
"""
1. iterare su tutte le feature (le colonne)
2. iterare sugli intervalli possibili di valori delle feature - capire le soglie
3. dividere y in due - avremo un sottoalbero sinistro e un sottoalbero destro
"""

In [ ]:
lista = [4,5,6,6,10,3,45,70]

In [39]:
X_train.shape[1]

45

In [43]:
s_list = np.unique(X_train[:,1])
s_list   

array([0., 1.])

In [47]:
s_list = np.unique(X_train[:,40])
s_list

array([17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28., 29.,
       30., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41., 42.,
       43., 44., 45., 46., 47., 48., 49., 50., 51., 52., 53., 54., 55.,
       56., 57., 58., 59., 60., 61., 62., 63., 64., 65., 66., 67., 68.,
       69., 70., 71., 72., 73., 74., 75., 76., 77., 78., 79., 80., 81.,
       82., 83., 84., 85., 86., 88., 90.])

In [49]:
X_train[:,40]

array([50., 31., 35., ..., 23., 64., 17.])

In [51]:
y_train[X_train[:,j] <= 17]

array([0., 0., 0., ..., 0., 0., 0.])

In [40]:
#TO DO calcolo del primo split (costruire f e soglia)

# Questa parte di codice serve per rappresentare un SOLO split
dec_list = []
queries = []

entropy_root = entropy(y_train) #entropia della radice
for j in range(X_train.shape[1]):
    s_list = np.unique(X_train[:,j])
    for s in s_list:
        y_left = y_train[X_train[:,j] <= s]
        y_right =  y_train[X_train[:,j] > s]
        
        n_l = len(y_left)
        n_r = len(y_right)
        n = len(y_train)
        
        if (n_l > 0  and n_r > 0): #per evitare di avere sottospazi con nessun campione #modificabile
            
            e_left = entropy(y_left)
            e_right = entropy(y_right)
            
            #decremo di impurità
            dec = entropy_root - (n_l / n * e_left +  n_r /n * e_right)
            dec_list += [dec]
            queries += [{"feature":j, "soglia":s, "e_left":e_left, "e_right":e_right, "nl":n_l, "nr":n_r}]


In [41]:
i = np.argmax(dec_list)
print(queries[i])

{'feature': 9, 'soglia': 0.0, 'e_left': 0.3603224869659964, 'e_right': 0.9943191863622456, 'nl': 13050, 'nr': 11524}


In [42]:
queries

[{'feature': 0,
  'soglia': 0.0,
  'e_left': 0.8038174817446023,
  'e_right': 0.9673914091689424,
  'nl': 23795,
  'nr': 779},
 {'feature': 1,
  'soglia': 0.0,
  'e_left': 0.8054224847626492,
  'e_right': 0.8813626661553357,
  'nl': 22871,
  'nr': 1703},
 {'feature': 2,
  'soglia': 0.0,
  'e_left': 0.9224119004601422,
  'e_right': 0.7579767275662812,
  'nl': 6471,
  'nr': 18103},
 {'feature': 3,
  'soglia': 0.0,
  'e_left': 0.7927748731974542,
  'e_right': 0.9915908465278448,
  'nl': 23684,
  'nr': 890},
 {'feature': 4,
  'soglia': 0.0,
  'e_left': 0.8062102224656409,
  'e_right': 0.8632131232295028,
  'nl': 22534,
  'nr': 2040},
 {'feature': 5,
  'soglia': 0.0,
  'e_left': 0.8094710570123719,
  'e_right': 0.8513057078061381,
  'nl': 23527,
  'nr': 1047},
 {'feature': 6,
  'soglia': 0.0,
  'e_left': 0.8115683760664325,
  'e_right': 0,
  'nl': 24562,
  'nr': 12},
 {'feature': 7,
  'soglia': 0.0,
  'e_left': 0.8453873502853849,
  'e_right': 0.49301299867475795,
  'nl': 21195,
  'nr': 337

#utilizzare la libreria DecisionTreeClassifier()

https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html

In [59]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report

dt = DecisionTreeClassifier(random_state=44)
dt.fit(X_train,y_train)
y_pred = dt.predict(X_test)
print(classification_report(y_test,y_pred))


              precision    recall  f1-score   support

         0.0       0.87      0.88      0.88      4639
         1.0       0.62      0.60      0.61      1505

    accuracy                           0.81      6144
   macro avg       0.75      0.74      0.74      6144
weighted avg       0.81      0.81      0.81      6144



In [61]:
dt.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'presort': 'deprecated',
 'random_state': 44,
 'splitter': 'best'}